@echo off

rem  This script validates a few sample OData responses against the JSON Schema files generated by transform.cmd
rem
rem  Prerequisites
rem  - ajv-cli is installed - npm install -g ajv-cli

call ajv validate -s ..\schemas\json-schema-draft-07.json -d ..\schemas\csdl.schema.json

call ajv validate -s ..\schemas\csdl.schema.json -d *.json
