@echo off

rem  This script validates the csdl.schema.json file against JSON Schema draft 07
rem  Then it validates the example CSDL JSON files generated by transform.cmd against csdl.schema.json
rem
rem  Prerequisites
rem  - ajv-cli is installed - npm install -g ajv-cli

call ajv validate -s ..\schemas\json-schema-draft-07.json -d ..\schemas\csdl.schema.json

call ajv validate -s ..\schemas\csdl.schema.json -d *.json
